### ISSUE TITLE
Домашнее задание по тестированию

### ISSUE THREAD

**Issue by tiny-kottan** [Quodnon/catwork-js-2016#17]
https://github.com/timoxley/functional-javascript-workshop - complete 'Function Spies' exercise.
Investigate following questions:
  1) What are stubs, mocks? What is the difference?
  2) What is the difference between TDD and BDD?
Read about several test frameworks / setups, pick one (qunit, jasmine, mocha, ava, tape). 
Do Kata #1 using it.

**Comment by mykola-den** [comment]
[\- **Function Spies**](https://github.com/Quodnon/catwork-js-2016/blob/master/week06/testing/program.js)
[\- **coding cata in 2 hours**](https://github.com/Quodnon/catwork-js-2016/tree/master/week05/homework)
