### ISSUE TITLE
Домашнее задание по Node

### ISSUE THREAD

**Issue by tiny-kottan** [Quodnon/catwork-js-2016#18]
Complete https://gist.github.com/mkozhukharenko/74c2d55ff53f67670a6a7e1f0c37f1b0

**Comment by mykola-den** [comment]
[npm start](https://github.com/Quodnon/catwork-js-2016/tree/master/week07/homework)

установка как:
git сlone "root repo"=> cd week07/homework => npm init =>npm install =>npm start
